service: imdb-api

params:
  default: 
    tableName: imdb-${sls:stage}
    domainName: ${sls:stage}-imdb.demos.danwakeem.com
  prod:
    domainName: imdb.demos.danwakeem.com

provider:
  name: aws
  runtime: nodejs20.x
  versionFunctions: false
  logRetentionInDays: 3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ MoviesTable, Arn ]
  environment:
    TABLE_NAME: ${param:tableName}

plugins:
  - serverless-esbuild
  - serverless-domain-manager

custom:
  tableName: 'imdb-${sls:stage}'
  customDomain:
    domainName: ${param:domainName}
    basePath: imdb
    autoDomain: true
    apiType: "http"
    endpointType: "regional"
  esbuild:
    bundle: true
    minify: false
    packager: yarn

package:
  patterns:
    - '!fern/**'
    - '!.envrc'
    - '!README.md'
    - '!sdk/**'

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
